language: python
sudo: false
python:
  - "3.2"
  - "3.3"
  - "3.4"
# command to install dependencies
install:
  - "pip install -r requirements.txt"
  - "pip install -r requirements-dev.txt"
  - pip install coveralls
# command to run tests
script: coverage run --source huawei_3g setup.py test
after_success: coveralls